name: onedriveBitToOnedrive_junmark Sync
on:
    push:
    schedule:
        - cron: '10 4 * * *'
jobs:
    OnedriveBitToOnedrive_junmark:
        name: OneDriveBit to OneDrive_junmark Sync
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@master
        - name: Download and Install rclone
          run: sudo curl https://rclone.org/install.sh | sudo bash
        - name: Decrypt config
          run: |
              bash decrypt.sh
          env:
              GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE}}
        - name: OnedriveBitToOnedrive_junmark
          run: |
              # Start Mission 
              bash OnedriveBitToOnedrive_junmark.sh
