name: Drive Sync
on:
    push:
    schedule:
        - cron: '0 0/6 * * *'
jobs:
    odgd:
        name: OneDrive_Business to OneDrive Sync
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@master
        - name: Download and Install rclone
          run: sudo curl https://rclone.org/install.sh | sudo bash
        - name: Decrypt config
          run: |
              bash decrypt.sh
          env:
              GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE}}
        - name: copy
          run: |
              # Start Mission 
              bash copy.sh

   
