name: Whole Backup
on:
    push:
    schedule:
        - cron: '0 0/6 * * *'
jobs:
    backup:
        name: WholeBackup
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@master
        - name: Download and Install rclone
          run: sudo curl https://rclone.org/install.sh | sudo bash
        - name: Decrypt config
          run: |
              bash decrypt.sh
          env:
              GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE}}
        - name: Backup
          run: |
              # Start Mission 
              bash wholebackup.sh
